test download

diff --git a/.github/workflows/generate-doc-and-notify-smart-doc.yml b/.github/workflows/generate-doc-and-notify-smart-doc.yml
--- a/.github/workflows/generate-doc-and-notify-smart-doc.yml
+++ b/.github/workflows/generate-doc-and-notify-smart-doc.yml
@@ -30,58 +30,17 @@ jobs:
           file smart-doc-source.zip
           echo "File size:"
           ls -lh smart-doc-source.zip
+
+      # Step 3: Create Directory and Move File
+      - name: Create Directory and Move File
+        run: |
           mkdir -p ~/.m2/repository/com/github/linwumingshi
           mv smart-doc-source.zip ~/.m2/repository/com/github/linwumingshi/
-          echo "Unzipping artifact..."
-          unzip -d ~/.m2/repository/com/github/linwumingshi smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat smart-doc-source.zip && exit 1)
+          echo "Listing files in target directory:"
+          ls -lh ~/.m2/repository/com/github/linwumingshi
 
-
-      # Step 3: Checkout Plugin Repository
-      - name: Checkout Plugin Repository
-        uses: actions/checkout@v4
-
-      # Step 4: Set up JDK 11
-      - name: Set up JDK 11
-        uses: actions/setup-java@v4
-        with:
-          java-version: '11'
-          distribution: 'temurin'
-
-      # Step 5: Create Directory for Unzipping
-      - name: Create Directory for Unzipping
-        run: mkdir -p ~/.m2/repository/com/github/linwumingshi
-
-      # Step 6: List Directory
-      - name: List Directory
-        run: |
-          echo "Current directory:"
-          pwd
-          echo "Listing files:"
-          ls -lh
-
-      # Step 7: Check if file exists
-      - name: Check if file exists
-        run: |
-          if [ -f smart-doc-source.zip ]; then
-            echo "File exists."
-          else
-            echo "File does not exist."
-            exit 1
-          fi
-
-      # Step 8: Unzip Artifact
+      # Step 4: Unzip Artifact
       - name: Unzip Artifact
         run: |
           echo "Unzipping artifact..."
-          unzip -d ~/.m2/repository/com/github/linwumingshi smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat smart-doc-source.zip && exit 1)
-
-      # Step 9: Set up Maven
-      - name: Set up Maven
-        uses: actions/setup-java@v4
-        with:
-          java-version: '11'
-          maven-version: '3.8.6'
-
-      # Step 10: Build and Install Plugin
-      - name: Build and Install Plugin
-        run: mvn install
+          unzip -d ~/.m2/repository/com/github/linwumingshi ~/.m2/repository/com/github/linwumingshi/smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat ~/.m2/repository/com/github/linwumingshi/smart-doc-source.zip && exit 1)
