test smart-doc-example

diff --git a/.github/workflows/generate-doc-and-notify-smart-doc.yml b/.github/workflows/generate-doc-and-notify-smart-doc.yml
--- a/.github/workflows/generate-doc-and-notify-smart-doc.yml
+++ b/.github/workflows/generate-doc-and-notify-smart-doc.yml
@@ -9,6 +9,19 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout Example Repository
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v4
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+
+      - name: Build and Install Plugin
+        run: mvn install
+
+
       # Step 1: Set Artifact URL
       - name: Set Artifact URL
         run: |
@@ -34,14 +47,23 @@ jobs:
       # Step 3: Create Directory and Move File
       - name: Create Directory and Move File
         run: |
-          mkdir -p ~/.m2/repository/com/github/linwumingshi
-          mv smart-doc-source.zip ~/.m2/repository/com/github/linwumingshi/
+          mkdir -p ~/.m2/repository/com/ly/smart-doc
+          mv smart-doc-source.zip ~/.m2/repository/com/ly/smart-doc/
           echo "Listing files in target directory:"
-          ls -lh ~/.m2/repository/com/github/linwumingshi
+          ls -lh ~/.m2/repository/com/ly/smart-doc
 
       # Step 4: Unzip Artifact
       - name: Unzip Artifact
         run: |
           echo "Unzipping artifact..."
-          unzip -d ~/.m2/repository/com/github/linwumingshi ~/.m2/repository/com/github/linwumingshi/smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat ~/.m2/repository/com/github/linwumingshi/smart-doc-source.zip && exit 1)
-          ls -lh ~/.m2/repository/com/github/linwumingshi
+          unzip -d ~/.m2/repository/com/ly/smart-doc ~/.m2/repository/com/ly/smart-doc/smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat ~/.m2/repository/com/ly/smart-doc/smart-doc-source.zip && exit 1)
+          ls -lh ~/.m2/repository/com/ly/smart-doc
+
+      - name: Build and Install Plugin
+        run: mvn install
+
+
+      - name: generate-doc
+        run: mvn smart-doc:html
+
+
