test download

diff --git a/.github/workflows/generate-doc-and-notify-smart-doc.yml b/.github/workflows/generate-doc-and-notify-smart-doc.yml
--- a/.github/workflows/generate-doc-and-notify-smart-doc.yml
+++ b/.github/workflows/generate-doc-and-notify-smart-doc.yml
@@ -16,7 +16,6 @@ jobs:
             echo "Error: ARTIFACT_ID is not set."
             exit 1
           fi
-          # Explicitly specify the A repository for artifact download
           ARTIFACT_URL="https://api.github.com/repos/linwumingshi/common/actions/artifacts/${ARTIFACT_ID}/zip"
           echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_ENV
 
@@ -31,4 +30,5 @@ jobs:
 
       - name: Unzip Artifact
         run: |
-          unzip smart-doc-source.zip -d ~/.m2/repository/com/github/linwumingshi || (echo "Unzip failed, printing file content:" && cat smart-doc-source.zip && exit 1)
+          echo "Unzipping artifact..."
+          unzip -d ~/.m2/repository/com/github/linwumingshi smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat smart-doc-source.zip && exit 1)
